language: node_js
node_js: "12"
cache: npm

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on: 
    tags: true



